#!/bin/bash

source $HOME/bin/ssUpl.conf
name="$HOME/Pictures/Screenshots/"$(printf %q $(date '+%Y-%m-%d-%T'))

if [ $1 == "-z" ]; then

    gnome-screenshot -c -f "$name.png" $2
    photo="document=@$name.png"
    method="SendDocument"
else

    gnome-screenshot -c -f "$name.png" $1
    photo="photo=@$name.png"
    method="sendPhoto"
fi

curl -v -F "chat_id=$chatId" -F $photo "https://api.telegram.org/bot$botToken/$method"
